name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run update-version script
        run: |
          chmod +x update-version.sh
          ./update-version.sh

      # שלב 4: Commit במידה ויש שינויים
      - name: Commit updated version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git reset --hard origin/main
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          if git status --porcelain | grep -q "pom.xml"; then
            git add pom.xml
            git commit -m "Update patch version automatically"
            git push origin main
          else
            echo "No changes detected, skipping commit."
          fi

      # שלב 5: בניית Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # שלב 6: התחברות ל-Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # שלב 7: Push ל-Docker Hub
      - name: Push Docker Image
        run: |
          docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d --name my-app-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/my-app:latest
